site_name: EZtCloud文档中心

site_url: https://children1987.github.io/eztcloud-docs/
use_directory_urls: true

plugins:
  - search
  - mermaid2

theme:
  language: zh
  name: material
  features:
    - search.suggest
    - search.highlight
    - toc.follow
    - content.action.edit
    - content.action.view
    #- navigation.tracking
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      title: 摘要
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 考虑到md文档对其它工具的兼容性，暂不使用，而是用extra.css替代
  # - pymdownx.details
  # - admonition

extra:
  homepage: https://www.eztcloud.com/
  generator: true

extra_css:
  - stylesheets/extra.css

edit_uri: https://github.com/children1987/eztcloud-docs/tree/main/docs

nav:
  - 介绍:
    - 文档约定: 文档约定.md
    - EZtCloud是什么？: EZtCloud是什么？.md
    - EZtCloud核心概念: EZtCloud核心概念.md

  - 设备接入:
    - 设备联网方式: 设备联网方式.md
    - 设备接入协议: 设备接入协议.md
    - 设备快速连接: 设备快速连接.md
    - 设备MQTT接入协议: 设备MQTT接入协议.md
    - 一级子设备MQTT接入协议: 一级子设备MQTT接入协议.md
    - 子设备MQTT接入协议: 子设备MQTT接入协议.md
    - 设备TCP接入协议: 设备TCP接入协议.md
    - 设备通过DTU接入: 设备通过DTU接入.md

  - 设备信息调试:
    - 设备消息调试: 设备消息调试.md

  - 设备类型:
    - 创建设备类型: 创建设备类型.md
    - 功能定义: 功能定义.md
    - 自定义数据流: 自定义数据流.md
    - Modbus寄存器设置: Modbus寄存器设置.md
    - 个性化UI: 个性化UI.md

  - 规则引擎:
    - 创建规则引擎: 创建规则引擎.md
    - 属性上报预处理: 属性上报预处理.md
    - 属性上报: 属性上报.md
    - 事件上报: 事件上报.md
    - 自定义数据上报: 自定义数据上报.md
    - 云函数内置函数库: 云函数内置函数库.md

  - 定时任务:
    - 创建任务: 创建任务.md
    - 属性下发任务: 属性下发任务.md
    - 命令下发任务: 命令下发任务.md
    - 自定义下发任务: 自定义下发任务.md

  - 告警通知:
    - 告警规则: 告警规则.md
    - 告警通知: 告警通知.md
    - 告警历史: 告警历史.md
    
  - 设备维护:
    - OTA固件升级: OTA固件升级.md

  - API:
    - API 概述: API 概述.md
    - HTTPS API: HTTPS API.md
    - MQTT API: MQTT API.md

  - Topic映射:
    - Topic映射: Topic映射.md
